global:
  runner:
    os_image: ubuntu

task1: 
 deploy-to-dev:
    steps:
      - checkout
      - commands:
      # Install NVM (Node Version Manager) and Node.js
- curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
- source ~/.bashrc
- nvm install v20.5.1
- nvm list

# Deploy the HTML file to Azure Storage
- az storage blob upload-batch --account-name $AZURE_STORAGE_ACCOUNT --account-key $AZURE_STORAGE_KEY --destination $AZURE_CONTAINER_NAME --source public --pattern '*'

  # generate coverage reports
      - html:
          dir: htmlcov
