global:
  runner:
    os_image: ubuntu

tasks:
  deploy-to-dev:
    steps:
      - checkout
      - run: |
          az login
          az storage blob upload --account-name razorops --account-key m8WEGw3C72OhMh3BDlDRYB6ScEVrH+kURuAs9tWJ2iZjq2Vw49s5mOmaW6ARhn8hvLtwPiVzaKma+AStx38LHg== --container-name new1 --name myblob --type block --content-type "text/plain" --file /home/sravani/Staticwebsite/index.html

      - reports/html:
          dir: coverage
          index: index.html
