global:
  runner:
    os_image: ubuntu

task1: 
  - unit-tests:
    runner: SravaniBikkina/staticwebsite
task2:
  - build-static-website:
    steps:
      - checkout
      - build/website:
         htmlfile: index.html
         errorfile: error.html
  # generate coverage reports
      - html:
          dir: htmlcov
