global:
  runner:
    os_image: ubuntu

tasks:
 

tasks:
  deploy-to-dev:
    steps:
      - checkout
      - run: |
        $ az storage blob upload-batch --destination '$web' --source razorops --pattern '*'
        
    - reports/html:
        dir: coverage
        index: index.html
