global:
  runner:
    os_image: ubuntu

tasks:
  login to azure:
    steps:
      - checkout:
      - command: 
            - az login
  
      - reports/html:
          dir: coverage
          index: index.html
