global:
  runner:
    os_image: ubuntu

task: 
  - unit-tests:
    runner: SravaniBikkina/staticwebsite
  - build-static-website:
    steps:
      - checkout
      - build/website:
         htmlfile: index.html
         
      - junit: test-reports/*.xml
      - html:
          dir: htmlcov
