global:
  runner:
    os_image: ubuntu

tasks:
  deploy-to-dev:
    steps:
      - checkout
      - run: |
          - az login --service-principal --username APP_ID --password APP_SECRET --tenant TENANT_ID
          - az storage blob upload --account-name razorops --container-name '$web' --file index.html --auth-mode login
           
      - reports/html:
          dir: coverage
          index: index.html
