global:
  runner:
    os_image: ubuntu

tasks:
  deploy-to-dev:
    steps:
      - checkout
      - run: |
        az storage blob upload-batch --destination razorops --source ~/Static\ website --pattern '*'
     
      - reports/html:
          dir: coverage
          index: index.html
