global:
  runner:
    os_image: ubuntu

tasks:
  deploy-to-dev:
    steps:
      - checkout
      - run: |
          - az login --service-principal -u $appId -p $password --tenant $tenant
          az storage blob upload-batch \
            --account-name razorops \
            --account-key m8WEGw3C72OhMh3BDlDRYB6ScEVrH+kURuAs9tWJ2iZjq2Vw49s5mOmaW6ARhn8hvLtwPiVzaKma+AStx38LHg== \
            --destination '$web' \
            --source 'Staticwebsite'

      - reports/html:
          dir: coverage
          index: index.html
