global:
  runner:
    os_image: ubuntu

tasks:
  deploy-to-dev:
    steps:
      - checkout
      - run: |
          az login
          az role assignment create --role "Storage Blob Data owner" --assignee 663652a1-e026-447b-a696-45be055b1e8d --scope /subscriptions/fbb783fe-8aa0-4b09-bee5-fbc5f9b2b5d1/resourceGroups/staticwebsitehosting/providers/Microsoft.Storage/storageAccounts/razorops
          az storage blob upload-batch --account-name razorops --container-name '$web' --file index.html --auth-mode login
           
      - reports/html:
          dir: coverage
          index: index.html
