global:
  runner:
    os_image: ubuntu

tasks:
  deploy-to-dev:
    steps:
      - checkout
      - run: |
           azcopy copy 'C:\myDirectory\*' 'https://razorops.blob.core.windows.net/$web/razorops'

      - reports/html:
          dir: coverage
          index: index.html
