global:
  runner:
    os_image: ubuntu

tasks:
  deploy-to-dev:
    steps:
      - checkout
      - run: |
           az storage blob upload-batch -d $web -s razorops --pattern '*'
     
      - reports/html:
          dir: coverage
          index: index.html
