global:
  runner:
    os_image: ubuntu

tasks:
  deploy-to-dev:
    steps:
      - checkout
      - run: |
          - az login --service-principal --username 663652a1-e026-447b-a696-45be055b1e8d --password imy8Q~FQI7upK4mGW4EoIfzIqpwN2e3zOlmaKcHA --tenant deeb017c-7497-4744-a63c-4e3cebb9cdd3 --allow-no-subscriptions
          - az storage blob upload --account-name razorops --container-name '$web' --file index.html --auth-mode login
           
      - reports/html:
          dir: coverage
          index: index.html
