global:
  runner:
    os_image: ubuntu

tasks:
  deploy-to-dev:
    steps:
      - checkout
      - commands:
            az login --service-principal -u $appId -p $password --tenant $tenant
            # Upload files to Azure Storage in the '$web' container of the 'razorops' account
            az storage blob upload-batch -s build/ -d '$web' --account-name razorops --overwrite true
      when: branch == 'main'
  
  deploy-to-stage:
    steps:
      - checkout
      - commands:
            # Log in using the service principal
            az login --service-principal -u $appId -p $password --tenant $tenant
            # Upload files to Azure Storage in the '$web' container of the 'razorops' account
            az storage blob upload-batch -s build/ -d '$web' --account-name razorops --overwrite true
      when: branch == 'main'
      - reports/html:
          dir: coverage
          index: index.html
