global:
  runner:
    os_image: ubuntu

tasks:
  deploy-to-dev:
    steps:
      - checkout
      - run: |
          az login
          az storage blob upload --account-name razorops --container-name '$web' --file index.html --auth-mode login
           
      - reports/html:
          dir: coverage
          index: index.html
