version: v2
global:
  runner:
    os_image: ubuntu
  variables:
    - RACK_ENV=test

- name: test-build
   tasks:
     steps:
       - checkout
       - commands:
         - sudo apt install python3
         - python3 -m http.server
  
  - name: deploy-to-dev
     tasks:
       steps:
        - checkout
        - commands: 
          - az login --service-principal -u $APP_ID -p $PASS --tenant $TENANT
          - az storage blob upload-batch -s build/ -d '$web' --account-name razorops --overwrite true
    when: branch == 'main'
     
  - reports/html:
      dir: coverage
      index: index.html
